# This file is auto-generated by scripts/generate_resources.py.
# Do not edit this file directly.

from __future__ import annotations

from collections.abc import Mapping, Sequence
from functools import cached_property
from typing import Any
from urllib.parse import quote

from .._generated import pydantic_gen as models
from .._transport import AsyncTransport, RequestOptions, SyncTransport


class _SyncResource:
    def __init__(self, transport: SyncTransport) -> None:
        self._transport = transport


class _AsyncResource:
    def __init__(self, transport: AsyncTransport) -> None:
        self._transport = transport


class SyncHealthResource(_SyncResource):
    def check(
        self,
        *,
        _request_options: RequestOptions | None = None,
    ) -> models.HealthCheckResponse:
        """Health check"""
        path = '/v1/health'
        query = None
        body = None
        return self._transport.request(
            'GET',
            path,
            response_model=models.HealthCheckResponse,
            query=query,
            body=body,
            options=_request_options,
        )

    def verify_access_key(
        self,
        *,
        _request_options: RequestOptions | None = None,
    ) -> models.HealthCheckAuthResponse:
        """Verify that the provided access key is valid"""
        path = '/v1/health/auth'
        query = None
        body = None
        return self._transport.request(
            'GET',
            path,
            response_model=models.HealthCheckAuthResponse,
            query=query,
            body=body,
            options=_request_options,
        )


class SyncConnectLinkedinResource(_SyncResource):
    def get_selection(
        self,
        token: str,
        *,
        _request_options: RequestOptions | None = None,
    ) -> models.GetLinkedInSelectionResponse:
        """Get pending LinkedIn account choices for headless mode"""
        path_values = models.GetLinkedInSelectionPath.model_validate(
            {'token': token}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        path = '/v1/connect/linkedin/selection/{token}'
        path = path.replace('{token}', quote(str(path_values['token']), safe=''))
        query = None
        body = None
        return self._transport.request(
            'GET',
            path,
            response_model=models.GetLinkedInSelectionResponse,
            query=query,
            body=body,
            options=_request_options,
        )

    def submit_selection(
        self,
        token: str,
        selected_account_ids: Sequence[str],
        *,
        _request_options: RequestOptions | None = None,
    ) -> models.SubmitLinkedInSelectionResponse:
        """Save selected LinkedIn accounts for headless mode"""
        path_values = models.SubmitLinkedInSelectionPath.model_validate(
            {'token': token}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        path = '/v1/connect/linkedin/selection/{token}'
        path = path.replace('{token}', quote(str(path_values['token']), safe=''))
        query = None
        body = models.SubmitLinkedInSelectionBody.model_validate(
            {'selectedAccountIds': selected_account_ids}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        return self._transport.request(
            'POST',
            path,
            response_model=models.SubmitLinkedInSelectionResponse,
            query=query,
            body=body,
            options=_request_options,
        )


class SyncConnectIntegrationsResource(_SyncResource):
    def disconnect(
        self,
        id: str,
        *,
        _request_options: RequestOptions | None = None,
    ) -> models.DisconnectIntegrationResponse:
        """Disconnect a platform integration"""
        path_values = models.DisconnectIntegrationPath.model_validate(
            {'id': id}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        path = '/v1/connect/integrations/{id}'
        path = path.replace('{id}', quote(str(path_values['id']), safe=''))
        query = None
        body = None
        return self._transport.request(
            'DELETE',
            path,
            response_model=models.DisconnectIntegrationResponse,
            query=query,
            body=body,
            options=_request_options,
        )

    def list(
        self,
        *,
        platform: models.ListIntegrationsPlatform | str | None = None,
        profile_id: str | None = None,
        q: str | None = None,
        limit: int | None = None,
        offset: int | None = None,
        sort: models.SortOrder | None = None,
        _request_options: RequestOptions | None = None,
    ) -> models.ListIntegrationsResponse:
        """List integrations connected to this project"""
        path = '/v1/connect/integrations'
        query = models.ListIntegrationsQuery.model_validate(
            {'platform': platform, 'profileId': profile_id, 'q': q, 'limit': limit, 'offset': offset, 'sort': sort}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        body = None
        return self._transport.request(
            'GET',
            path,
            response_model=models.ListIntegrationsResponse,
            query=query,
            body=body,
            options=_request_options,
        )


class SyncConnectResource(_SyncResource):
    def bluesky(
        self,
        identifier: str,
        password: str,
        *,
        redirect_uri: str | None = None,
        cancel_redirect_uri: str | None = None,
        headless: bool | None = None,
        profile_id: str | None = None,
        app_id: str | None = None,
        _request_options: RequestOptions | None = None,
    ) -> None:
        """Connect a Bluesky account via app password"""
        path = '/v1/connect/bluesky/auth'
        query = models.ConnectBlueskyQuery.model_validate(
            {'redirectUri': redirect_uri, 'cancelRedirectUri': cancel_redirect_uri, 'headless': headless, 'profileId': profile_id, 'appId': app_id}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        body = models.ConnectBlueskyBody.model_validate(
            {'identifier': identifier, 'password': password}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        return self._transport.request(
            'POST',
            path,
            response_model=None,
            query=query,
            body=body,
            options=_request_options,
        )

    def get_oauth_url(
        self,
        platform: models.GetOAuthUrlPlatform | str,
        *,
        redirect_uri: str | None = None,
        cancel_redirect_uri: str | None = None,
        headless: bool | None = None,
        profile_id: str | None = None,
        app_id: str | None = None,
        _request_options: RequestOptions | None = None,
    ) -> models.GetOAuthUrlResponse:
        """Get OAuth URL for a platform"""
        path_values = models.GetOAuthUrlPath.model_validate(
            {'platform': platform}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        path = '/v1/connect/{platform}'
        path = path.replace('{platform}', quote(str(path_values['platform']), safe=''))
        query = models.GetOAuthUrlQuery.model_validate(
            {'redirectUri': redirect_uri, 'cancelRedirectUri': cancel_redirect_uri, 'headless': headless, 'profileId': profile_id, 'appId': app_id}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        body = None
        return self._transport.request(
            'GET',
            path,
            response_model=models.GetOAuthUrlResponse,
            query=query,
            body=body,
            options=_request_options,
        )

    @cached_property
    def integrations(self) -> SyncConnectIntegrationsResource:
        return SyncConnectIntegrationsResource(self._transport)

    @cached_property
    def linkedin(self) -> SyncConnectLinkedinResource:
        return SyncConnectLinkedinResource(self._transport)


class SyncProfilesResource(_SyncResource):
    def create(
        self,
        name: str,
        *,
        description: str | None = None,
        _request_options: RequestOptions | None = None,
    ) -> models.CreateProfileResponse:
        """Create a profile"""
        path = '/v1/profiles/'
        query = None
        body = models.CreateProfileBody.model_validate(
            {'name': name, 'description': description}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        return self._transport.request(
            'POST',
            path,
            response_model=models.CreateProfileResponse,
            query=query,
            body=body,
            options=_request_options,
        )

    def delete(
        self,
        id: str,
        *,
        _request_options: RequestOptions | None = None,
    ) -> models.DeleteProfileResponse:
        """Delete a profile"""
        path_values = models.DeleteProfilePath.model_validate(
            {'id': id}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        path = '/v1/profiles/{id}'
        path = path.replace('{id}', quote(str(path_values['id']), safe=''))
        query = None
        body = None
        return self._transport.request(
            'DELETE',
            path,
            response_model=models.DeleteProfileResponse,
            query=query,
            body=body,
            options=_request_options,
        )

    def get(
        self,
        id: str,
        *,
        _request_options: RequestOptions | None = None,
    ) -> models.GetProfileResponse:
        """Get a single profile"""
        path_values = models.GetProfilePath.model_validate(
            {'id': id}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        path = '/v1/profiles/{id}'
        path = path.replace('{id}', quote(str(path_values['id']), safe=''))
        query = None
        body = None
        return self._transport.request(
            'GET',
            path,
            response_model=models.GetProfileResponse,
            query=query,
            body=body,
            options=_request_options,
        )

    def list(
        self,
        *,
        page: int | None = None,
        limit: int | None = None,
        name: str | None = None,
        _request_options: RequestOptions | None = None,
    ) -> models.ListProfilesResponse:
        """List profiles for this project"""
        path = '/v1/profiles/'
        query = models.ListProfilesQuery.model_validate(
            {'page': page, 'limit': limit, 'name': name}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        body = None
        return self._transport.request(
            'GET',
            path,
            response_model=models.ListProfilesResponse,
            query=query,
            body=body,
            options=_request_options,
        )

    def update(
        self,
        id: str,
        *,
        name: str | None = None,
        description: str | None = None,
        _request_options: RequestOptions | None = None,
    ) -> models.UpdateProfileResponse:
        """Update a profile"""
        path_values = models.UpdateProfilePath.model_validate(
            {'id': id}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        path = '/v1/profiles/{id}'
        path = path.replace('{id}', quote(str(path_values['id']), safe=''))
        query = None
        body = models.UpdateProfileBody.model_validate(
            {'name': name, 'description': description}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        return self._transport.request(
            'PATCH',
            path,
            response_model=models.UpdateProfileResponse,
            query=query,
            body=body,
            options=_request_options,
        )


class SyncAppsResource(_SyncResource):
    def create(
        self,
        platform: models.CreateAppPlatform | str,
        name: str,
        client_id: str,
        client_secret: str,
        *,
        image_url: str | None = None,
        _request_options: RequestOptions | None = None,
    ) -> models.CreateAppResponse:
        """Register your own OAuth app (Bring Your Own Keys)"""
        path = '/v1/apps/'
        query = None
        body = models.CreateAppBody.model_validate(
            {'platform': platform, 'name': name, 'clientId': client_id, 'clientSecret': client_secret, 'imageUrl': image_url}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        return self._transport.request(
            'POST',
            path,
            response_model=models.CreateAppResponse,
            query=query,
            body=body,
            options=_request_options,
        )

    def delete(
        self,
        id: str,
        *,
        _request_options: RequestOptions | None = None,
    ) -> models.DeleteAppResponse:
        """Delete an OAuth app"""
        path_values = models.DeleteAppPath.model_validate(
            {'id': id}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        path = '/v1/apps/{id}'
        path = path.replace('{id}', quote(str(path_values['id']), safe=''))
        query = None
        body = None
        return self._transport.request(
            'DELETE',
            path,
            response_model=models.DeleteAppResponse,
            query=query,
            body=body,
            options=_request_options,
        )

    def get(
        self,
        id: str,
        *,
        _request_options: RequestOptions | None = None,
    ) -> models.GetAppResponse:
        """Get a single OAuth app"""
        path_values = models.GetAppPath.model_validate(
            {'id': id}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        path = '/v1/apps/{id}'
        path = path.replace('{id}', quote(str(path_values['id']), safe=''))
        query = None
        body = None
        return self._transport.request(
            'GET',
            path,
            response_model=models.GetAppResponse,
            query=query,
            body=body,
            options=_request_options,
        )

    def list(
        self,
        *,
        platform: models.ListAppsPlatform | str | None = None,
        page: int | None = None,
        limit: int | None = None,
        name: str | None = None,
        _request_options: RequestOptions | None = None,
    ) -> models.ListAppsResponse:
        """List registered OAuth apps for this project"""
        path = '/v1/apps/'
        query = models.ListAppsQuery.model_validate(
            {'platform': platform, 'page': page, 'limit': limit, 'name': name}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        body = None
        return self._transport.request(
            'GET',
            path,
            response_model=models.ListAppsResponse,
            query=query,
            body=body,
            options=_request_options,
        )

    def update(
        self,
        id: str,
        *,
        name: str | None = None,
        image_url: str | None = None,
        client_secret: str | None = None,
        _request_options: RequestOptions | None = None,
    ) -> models.UpdateAppResponse:
        """Update an OAuth app"""
        path_values = models.UpdateAppPath.model_validate(
            {'id': id}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        path = '/v1/apps/{id}'
        path = path.replace('{id}', quote(str(path_values['id']), safe=''))
        query = None
        body = models.UpdateAppBody.model_validate(
            {'name': name, 'imageUrl': image_url, 'clientSecret': client_secret}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        return self._transport.request(
            'PATCH',
            path,
            response_model=models.UpdateAppResponse,
            query=query,
            body=body,
            options=_request_options,
        )


class SyncNotificationsResource(_SyncResource):
    def create(
        self,
        channel: models.CreateNotificationChannel | str,
        event_types: Sequence[models.CreateNotificationEventTypes | str],
        *,
        profile_id: str | None = None,
        only_scheduled_posts: bool | None = None,
        enabled: bool | None = None,
        webhook: models.CreateNotificationWebhook | Mapping[str, Any] | None = None,
        email: models.CreateNotificationEmail | Mapping[str, Any] | None = None,
        _request_options: RequestOptions | None = None,
    ) -> models.CreateNotificationResponse:
        """Create a notification subscription"""
        path = '/v1/notifications/'
        query = None
        body = models.CreateNotificationBody.model_validate(
            {'channel': channel, 'profileId': profile_id, 'eventTypes': event_types, 'onlyScheduledPosts': only_scheduled_posts, 'enabled': enabled, 'webhook': webhook, 'email': email}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        return self._transport.request(
            'POST',
            path,
            response_model=models.CreateNotificationResponse,
            query=query,
            body=body,
            options=_request_options,
        )

    def delete(
        self,
        id: str,
        *,
        _request_options: RequestOptions | None = None,
    ) -> models.DeleteNotificationResponse:
        """Delete a notification subscription"""
        path_values = models.DeleteNotificationPath.model_validate(
            {'id': id}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        path = '/v1/notifications/{id}'
        path = path.replace('{id}', quote(str(path_values['id']), safe=''))
        query = None
        body = None
        return self._transport.request(
            'DELETE',
            path,
            response_model=models.DeleteNotificationResponse,
            query=query,
            body=body,
            options=_request_options,
        )

    def get(
        self,
        id: str,
        *,
        _request_options: RequestOptions | None = None,
    ) -> models.GetNotificationResponse:
        """Get a notification subscription"""
        path_values = models.GetNotificationPath.model_validate(
            {'id': id}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        path = '/v1/notifications/{id}'
        path = path.replace('{id}', quote(str(path_values['id']), safe=''))
        query = None
        body = None
        return self._transport.request(
            'GET',
            path,
            response_model=models.GetNotificationResponse,
            query=query,
            body=body,
            options=_request_options,
        )

    def list(
        self,
        *,
        _request_options: RequestOptions | None = None,
    ) -> models.ListNotificationsResponse:
        """List notification subscriptions"""
        path = '/v1/notifications/'
        query = None
        body = None
        return self._transport.request(
            'GET',
            path,
            response_model=models.ListNotificationsResponse,
            query=query,
            body=body,
            options=_request_options,
        )

    def test(
        self,
        channel: models.TestNotificationChannel | str,
        *,
        profile_id: str | None = None,
        webhook: models.TestNotificationWebhook | Mapping[str, Any] | None = None,
        email: models.TestNotificationEmail | Mapping[str, Any] | None = None,
        _request_options: RequestOptions | None = None,
    ) -> models.TestNotificationResponse:
        """Test a notification destination before saving it"""
        path = '/v1/notifications/test'
        query = None
        body = models.TestNotificationBody.model_validate(
            {'channel': channel, 'profileId': profile_id, 'webhook': webhook, 'email': email}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        return self._transport.request(
            'POST',
            path,
            response_model=models.TestNotificationResponse,
            query=query,
            body=body,
            options=_request_options,
        )

    def update(
        self,
        id: str,
        *,
        profile_id: str | None = None,
        event_types: Sequence[models.UpdateNotificationEventTypes | str] | None = None,
        only_scheduled_posts: bool | None = None,
        enabled: bool | None = None,
        webhook: models.UpdateNotificationWebhook | Mapping[str, Any] | None = None,
        email: models.UpdateNotificationEmail | Mapping[str, Any] | None = None,
        _request_options: RequestOptions | None = None,
    ) -> models.UpdateNotificationResponse:
        """Update a notification subscription"""
        path_values = models.UpdateNotificationPath.model_validate(
            {'id': id}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        path = '/v1/notifications/{id}'
        path = path.replace('{id}', quote(str(path_values['id']), safe=''))
        query = None
        body = models.UpdateNotificationBody.model_validate(
            {'profileId': profile_id, 'eventTypes': event_types, 'onlyScheduledPosts': only_scheduled_posts, 'enabled': enabled, 'webhook': webhook, 'email': email}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        return self._transport.request(
            'PATCH',
            path,
            response_model=models.UpdateNotificationResponse,
            query=query,
            body=body,
            options=_request_options,
        )


class SyncPlatformsResource(_SyncResource):
    def list(
        self,
        *,
        _request_options: RequestOptions | None = None,
    ) -> models.ListPlatformsResponse:
        """List available platforms and their status"""
        path = '/v1/platforms'
        query = None
        body = None
        return self._transport.request(
            'GET',
            path,
            response_model=models.ListPlatformsResponse,
            query=query,
            body=body,
            options=_request_options,
        )


class SyncPostsScheduledResource(_SyncResource):
    def cancel(
        self,
        post_id: str,
        *,
        _request_options: RequestOptions | None = None,
    ) -> models.CancelScheduledPostResponse:
        """Cancel a scheduled post (moves it back to draft)"""
        path_values = models.CancelScheduledPostPath.model_validate(
            {'postId': post_id}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        path = '/v1/posts/scheduled/{postId}'
        path = path.replace('{postId}', quote(str(path_values['postId']), safe=''))
        query = None
        body = None
        return self._transport.request(
            'DELETE',
            path,
            response_model=models.CancelScheduledPostResponse,
            query=query,
            body=body,
            options=_request_options,
        )

    def list(
        self,
        *,
        limit: int | None = None,
        offset: int | None = None,
        sort: models.SortOrder | None = None,
        _request_options: RequestOptions | None = None,
    ) -> models.ListScheduledPostsResponse:
        """List all scheduled posts"""
        path = '/v1/posts/scheduled/'
        query = models.ListScheduledPostsQuery.model_validate(
            {'limit': limit, 'offset': offset, 'sort': sort}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        body = None
        return self._transport.request(
            'GET',
            path,
            response_model=models.ListScheduledPostsResponse,
            query=query,
            body=body,
            options=_request_options,
        )

    def reschedule(
        self,
        post_id: str,
        scheduled_for: str,
        *,
        timezone: str | None = None,
        _request_options: RequestOptions | None = None,
    ) -> models.ReschedulePostResponse:
        """Reschedule a post to a new time"""
        path_values = models.ReschedulePostPath.model_validate(
            {'postId': post_id}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        path = '/v1/posts/scheduled/{postId}'
        path = path.replace('{postId}', quote(str(path_values['postId']), safe=''))
        query = None
        body = models.ReschedulePostBody.model_validate(
            {'scheduledFor': scheduled_for, 'timezone': timezone}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        return self._transport.request(
            'PATCH',
            path,
            response_model=models.ReschedulePostResponse,
            query=query,
            body=body,
            options=_request_options,
        )


class SyncPostsResource(_SyncResource):
    def create(
        self,
        content: str,
        platforms: Sequence[models.CreatePostPlatforms | Mapping[str, Any] | models.CreatePostPlatforms_ | Mapping[str, Any] | models.CreatePostPlatforms_2 | Mapping[str, Any] | models.CreatePostPlatforms_3 | Mapping[str, Any] | models.CreatePostPlatforms_4 | Mapping[str, Any] | models.CreatePostPlatforms_5 | Mapping[str, Any] | models.CreatePostPlatforms_6 | Mapping[str, Any] | models.CreatePostPlatforms_7 | Mapping[str, Any] | models.CreatePostPlatforms_8 | Mapping[str, Any] | models.CreatePostPlatforms_9 | Mapping[str, Any]],
        *,
        media_items: Sequence[models.CreatePostMediaItems | Mapping[str, Any]] | None = None,
        publish_now: bool | None = None,
        scheduled_for: str | None = None,
        timezone: str | None = None,
        _request_options: RequestOptions | None = None,
    ) -> models.CreatePostResponse:
        """Publish a post to one or more social media platforms"""
        path = '/v1/posts/'
        query = None
        body = models.CreatePostBody.model_validate(
            {'content': content, 'mediaItems': media_items, 'platforms': platforms, 'publishNow': publish_now, 'scheduledFor': scheduled_for, 'timezone': timezone}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        return self._transport.request(
            'POST',
            path,
            response_model=models.CreatePostResponse,
            query=query,
            body=body,
            options=_request_options,
        )

    def delete(
        self,
        post_id: str,
        *,
        delete_from_platforms: bool | None = None,
        _request_options: RequestOptions | None = None,
    ) -> models.DeletePostResponse:
        """Delete a post by ID"""
        path_values = models.DeletePostPath.model_validate(
            {'postId': post_id}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        path = '/v1/posts/{postId}'
        path = path.replace('{postId}', quote(str(path_values['postId']), safe=''))
        query = models.DeletePostQuery.model_validate(
            {'deleteFromPlatforms': delete_from_platforms}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        body = None
        return self._transport.request(
            'DELETE',
            path,
            response_model=models.DeletePostResponse,
            query=query,
            body=body,
            options=_request_options,
        )

    def get(
        self,
        post_id: str,
        *,
        _request_options: RequestOptions | None = None,
    ) -> models.GetPostResponse:
        """Get a single post by ID"""
        path_values = models.GetPostPath.model_validate(
            {'postId': post_id}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        path = '/v1/posts/{postId}'
        path = path.replace('{postId}', quote(str(path_values['postId']), safe=''))
        query = None
        body = None
        return self._transport.request(
            'GET',
            path,
            response_model=models.GetPostResponse,
            query=query,
            body=body,
            options=_request_options,
        )

    def list(
        self,
        *,
        status: models.ListPostsStatus | str | None = None,
        platform: Sequence[models.ListPostsPlatform | str] | None = None,
        profile_id: str | None = None,
        created_after: str | None = None,
        created_before: str | None = None,
        scheduled_after: str | None = None,
        scheduled_before: str | None = None,
        limit: int | None = None,
        offset: int | None = None,
        sort: models.SortOrder | None = None,
        _request_options: RequestOptions | None = None,
    ) -> models.ListPostsResponse:
        """List all posts for the project"""
        path = '/v1/posts/'
        query = models.ListPostsQuery.model_validate(
            {'status': status, 'platform': platform, 'profileId': profile_id, 'createdAfter': created_after, 'createdBefore': created_before, 'scheduledAfter': scheduled_after, 'scheduledBefore': scheduled_before, 'limit': limit, 'offset': offset, 'sort': sort}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        body = None
        return self._transport.request(
            'GET',
            path,
            response_model=models.ListPostsResponse,
            query=query,
            body=body,
            options=_request_options,
        )

    @cached_property
    def scheduled(self) -> SyncPostsScheduledResource:
        return SyncPostsScheduledResource(self._transport)


class SyncMediaResource(_SyncResource):
    def upload(
        self,
        filename: str,
        mime_type: str,
        *,
        _request_options: RequestOptions | None = None,
    ) -> models.CreateMediaUploadResponse:
        """Get a presigned S3 URL to upload a media file"""
        path = '/v1/media/upload'
        query = None
        body = models.CreateMediaUploadBody.model_validate(
            {'filename': filename, 'mimeType': mime_type}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        return self._transport.request(
            'POST',
            path,
            response_model=models.CreateMediaUploadResponse,
            query=query,
            body=body,
            options=_request_options,
        )


class SyncAnalyticsResource(_SyncResource):
    def get(
        self,
        *,
        post_id: str | None = None,
        platform: models.Platform | None = None,
        account_id: str | None = None,
        source: models.GetAnalyticsSource | str | None = None,
        from_date: str | None = None,
        to_date: str | None = None,
        sort_by: models.GetAnalyticsSortBy | str | None = None,
        order: models.SortOrder | None = None,
        limit: int | None = None,
        page: int | None = None,
        _request_options: RequestOptions | None = None,
    ) -> models.GetAnalyticsResponse:
        """Get post analytics"""
        path = '/v1/analytics/'
        query = models.GetAnalyticsQuery.model_validate(
            {'postId': post_id, 'platform': platform, 'accountId': account_id, 'source': source, 'fromDate': from_date, 'toDate': to_date, 'sortBy': sort_by, 'order': order, 'limit': limit, 'page': page}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        body = None
        return self._transport.request(
            'GET',
            path,
            response_model=models.GetAnalyticsResponse,
            query=query,
            body=body,
            options=_request_options,
        )


class SyncUsageResource(_SyncResource):
    def get(
        self,
        *,
        profile_id: str | None = None,
        integration_id: str | None = None,
        from_: str | None = None,
        to: str | None = None,
        _request_options: RequestOptions | None = None,
    ) -> models.GetUsageResponse:
        """Get credit usage"""
        path = '/v1/usage/'
        query = models.GetUsageQuery.model_validate(
            {'profileId': profile_id, 'integrationId': integration_id, 'from': from_, 'to': to}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        body = None
        return self._transport.request(
            'GET',
            path,
            response_model=models.GetUsageResponse,
            query=query,
            body=body,
            options=_request_options,
        )


class SyncPinterestResource(_SyncResource):
    def get_boards(
        self,
        *,
        account_id: str | None = None,
        _request_options: RequestOptions | None = None,
    ) -> models.GetPinterestBoardsResponse:
        """List Pinterest boards for a connected account"""
        path = '/v1/pinterest/boards'
        query = models.GetPinterestBoardsQuery.model_validate(
            {'accountId': account_id}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        body = None
        return self._transport.request(
            'GET',
            path,
            response_model=models.GetPinterestBoardsResponse,
            query=query,
            body=body,
            options=_request_options,
        )


class SyncTiktokResource(_SyncResource):
    def get_creator_info(
        self,
        *,
        account_id: str | None = None,
        _request_options: RequestOptions | None = None,
    ) -> models.GetTikTokCreatorInfoResponse:
        """Fetch TikTok creator info for a connected account"""
        path = '/v1/tiktok/creator-info'
        query = models.GetTikTokCreatorInfoQuery.model_validate(
            {'accountId': account_id}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        body = None
        return self._transport.request(
            'GET',
            path,
            response_model=models.GetTikTokCreatorInfoResponse,
            query=query,
            body=body,
            options=_request_options,
        )


class SyncAiResource(_SyncResource):
    def generate_image(
        self,
        description: str,
        *,
        aspect_ratio: models.AiGenerateImageAspectRatio | str | None = None,
        style: models.AiGenerateImageStyle | str | None = None,
        reference_image_urls: Sequence[str] | None = None,
        asset_image_urls: Sequence[str] | None = None,
        reference_image_url: str | None = None,
        _request_options: RequestOptions | None = None,
    ) -> models.AiGenerateImageResponse:
        """Generate a social media image from a description"""
        path = '/v1/ai/image'
        query = None
        body = models.AiGenerateImageBody.model_validate(
            {'description': description, 'aspectRatio': aspect_ratio, 'style': style, 'referenceImageUrls': reference_image_urls, 'assetImageUrls': asset_image_urls, 'referenceImageUrl': reference_image_url}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        return self._transport.request(
            'POST',
            path,
            response_model=models.AiGenerateImageResponse,
            query=query,
            body=body,
            options=_request_options,
        )

    def write(
        self,
        description: str,
        *,
        platforms: Sequence[models.AiWriteContentPlatforms | str] | None = None,
        existing_content: str | None = None,
        _request_options: RequestOptions | None = None,
    ) -> models.AiWriteContentResponse:
        """Generate a social media caption from a description"""
        path = '/v1/ai/write'
        query = None
        body = models.AiWriteContentBody.model_validate(
            {'description': description, 'platforms': platforms, 'existingContent': existing_content}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        return self._transport.request(
            'POST',
            path,
            response_model=models.AiWriteContentResponse,
            query=query,
            body=body,
            options=_request_options,
        )


class SyncPostPeerResources(_SyncResource):
    @cached_property
    def ai(self) -> SyncAiResource:
        return SyncAiResource(self._transport)

    @cached_property
    def analytics(self) -> SyncAnalyticsResource:
        return SyncAnalyticsResource(self._transport)

    @cached_property
    def apps(self) -> SyncAppsResource:
        return SyncAppsResource(self._transport)

    @cached_property
    def connect(self) -> SyncConnectResource:
        return SyncConnectResource(self._transport)

    @cached_property
    def health(self) -> SyncHealthResource:
        return SyncHealthResource(self._transport)

    @cached_property
    def media(self) -> SyncMediaResource:
        return SyncMediaResource(self._transport)

    @cached_property
    def notifications(self) -> SyncNotificationsResource:
        return SyncNotificationsResource(self._transport)

    @cached_property
    def pinterest(self) -> SyncPinterestResource:
        return SyncPinterestResource(self._transport)

    @cached_property
    def platforms(self) -> SyncPlatformsResource:
        return SyncPlatformsResource(self._transport)

    @cached_property
    def posts(self) -> SyncPostsResource:
        return SyncPostsResource(self._transport)

    @cached_property
    def profiles(self) -> SyncProfilesResource:
        return SyncProfilesResource(self._transport)

    @cached_property
    def tiktok(self) -> SyncTiktokResource:
        return SyncTiktokResource(self._transport)

    @cached_property
    def usage(self) -> SyncUsageResource:
        return SyncUsageResource(self._transport)


class AsyncHealthResource(_AsyncResource):
    async def check(
        self,
        *,
        _request_options: RequestOptions | None = None,
    ) -> models.HealthCheckResponse:
        """Health check"""
        path = '/v1/health'
        query = None
        body = None
        return await self._transport.request(
            'GET',
            path,
            response_model=models.HealthCheckResponse,
            query=query,
            body=body,
            options=_request_options,
        )

    async def verify_access_key(
        self,
        *,
        _request_options: RequestOptions | None = None,
    ) -> models.HealthCheckAuthResponse:
        """Verify that the provided access key is valid"""
        path = '/v1/health/auth'
        query = None
        body = None
        return await self._transport.request(
            'GET',
            path,
            response_model=models.HealthCheckAuthResponse,
            query=query,
            body=body,
            options=_request_options,
        )


class AsyncConnectLinkedinResource(_AsyncResource):
    async def get_selection(
        self,
        token: str,
        *,
        _request_options: RequestOptions | None = None,
    ) -> models.GetLinkedInSelectionResponse:
        """Get pending LinkedIn account choices for headless mode"""
        path_values = models.GetLinkedInSelectionPath.model_validate(
            {'token': token}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        path = '/v1/connect/linkedin/selection/{token}'
        path = path.replace('{token}', quote(str(path_values['token']), safe=''))
        query = None
        body = None
        return await self._transport.request(
            'GET',
            path,
            response_model=models.GetLinkedInSelectionResponse,
            query=query,
            body=body,
            options=_request_options,
        )

    async def submit_selection(
        self,
        token: str,
        selected_account_ids: Sequence[str],
        *,
        _request_options: RequestOptions | None = None,
    ) -> models.SubmitLinkedInSelectionResponse:
        """Save selected LinkedIn accounts for headless mode"""
        path_values = models.SubmitLinkedInSelectionPath.model_validate(
            {'token': token}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        path = '/v1/connect/linkedin/selection/{token}'
        path = path.replace('{token}', quote(str(path_values['token']), safe=''))
        query = None
        body = models.SubmitLinkedInSelectionBody.model_validate(
            {'selectedAccountIds': selected_account_ids}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        return await self._transport.request(
            'POST',
            path,
            response_model=models.SubmitLinkedInSelectionResponse,
            query=query,
            body=body,
            options=_request_options,
        )


class AsyncConnectIntegrationsResource(_AsyncResource):
    async def disconnect(
        self,
        id: str,
        *,
        _request_options: RequestOptions | None = None,
    ) -> models.DisconnectIntegrationResponse:
        """Disconnect a platform integration"""
        path_values = models.DisconnectIntegrationPath.model_validate(
            {'id': id}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        path = '/v1/connect/integrations/{id}'
        path = path.replace('{id}', quote(str(path_values['id']), safe=''))
        query = None
        body = None
        return await self._transport.request(
            'DELETE',
            path,
            response_model=models.DisconnectIntegrationResponse,
            query=query,
            body=body,
            options=_request_options,
        )

    async def list(
        self,
        *,
        platform: models.ListIntegrationsPlatform | str | None = None,
        profile_id: str | None = None,
        q: str | None = None,
        limit: int | None = None,
        offset: int | None = None,
        sort: models.SortOrder | None = None,
        _request_options: RequestOptions | None = None,
    ) -> models.ListIntegrationsResponse:
        """List integrations connected to this project"""
        path = '/v1/connect/integrations'
        query = models.ListIntegrationsQuery.model_validate(
            {'platform': platform, 'profileId': profile_id, 'q': q, 'limit': limit, 'offset': offset, 'sort': sort}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        body = None
        return await self._transport.request(
            'GET',
            path,
            response_model=models.ListIntegrationsResponse,
            query=query,
            body=body,
            options=_request_options,
        )


class AsyncConnectResource(_AsyncResource):
    async def bluesky(
        self,
        identifier: str,
        password: str,
        *,
        redirect_uri: str | None = None,
        cancel_redirect_uri: str | None = None,
        headless: bool | None = None,
        profile_id: str | None = None,
        app_id: str | None = None,
        _request_options: RequestOptions | None = None,
    ) -> None:
        """Connect a Bluesky account via app password"""
        path = '/v1/connect/bluesky/auth'
        query = models.ConnectBlueskyQuery.model_validate(
            {'redirectUri': redirect_uri, 'cancelRedirectUri': cancel_redirect_uri, 'headless': headless, 'profileId': profile_id, 'appId': app_id}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        body = models.ConnectBlueskyBody.model_validate(
            {'identifier': identifier, 'password': password}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        return await self._transport.request(
            'POST',
            path,
            response_model=None,
            query=query,
            body=body,
            options=_request_options,
        )

    async def get_oauth_url(
        self,
        platform: models.GetOAuthUrlPlatform | str,
        *,
        redirect_uri: str | None = None,
        cancel_redirect_uri: str | None = None,
        headless: bool | None = None,
        profile_id: str | None = None,
        app_id: str | None = None,
        _request_options: RequestOptions | None = None,
    ) -> models.GetOAuthUrlResponse:
        """Get OAuth URL for a platform"""
        path_values = models.GetOAuthUrlPath.model_validate(
            {'platform': platform}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        path = '/v1/connect/{platform}'
        path = path.replace('{platform}', quote(str(path_values['platform']), safe=''))
        query = models.GetOAuthUrlQuery.model_validate(
            {'redirectUri': redirect_uri, 'cancelRedirectUri': cancel_redirect_uri, 'headless': headless, 'profileId': profile_id, 'appId': app_id}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        body = None
        return await self._transport.request(
            'GET',
            path,
            response_model=models.GetOAuthUrlResponse,
            query=query,
            body=body,
            options=_request_options,
        )

    @cached_property
    def integrations(self) -> AsyncConnectIntegrationsResource:
        return AsyncConnectIntegrationsResource(self._transport)

    @cached_property
    def linkedin(self) -> AsyncConnectLinkedinResource:
        return AsyncConnectLinkedinResource(self._transport)


class AsyncProfilesResource(_AsyncResource):
    async def create(
        self,
        name: str,
        *,
        description: str | None = None,
        _request_options: RequestOptions | None = None,
    ) -> models.CreateProfileResponse:
        """Create a profile"""
        path = '/v1/profiles/'
        query = None
        body = models.CreateProfileBody.model_validate(
            {'name': name, 'description': description}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        return await self._transport.request(
            'POST',
            path,
            response_model=models.CreateProfileResponse,
            query=query,
            body=body,
            options=_request_options,
        )

    async def delete(
        self,
        id: str,
        *,
        _request_options: RequestOptions | None = None,
    ) -> models.DeleteProfileResponse:
        """Delete a profile"""
        path_values = models.DeleteProfilePath.model_validate(
            {'id': id}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        path = '/v1/profiles/{id}'
        path = path.replace('{id}', quote(str(path_values['id']), safe=''))
        query = None
        body = None
        return await self._transport.request(
            'DELETE',
            path,
            response_model=models.DeleteProfileResponse,
            query=query,
            body=body,
            options=_request_options,
        )

    async def get(
        self,
        id: str,
        *,
        _request_options: RequestOptions | None = None,
    ) -> models.GetProfileResponse:
        """Get a single profile"""
        path_values = models.GetProfilePath.model_validate(
            {'id': id}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        path = '/v1/profiles/{id}'
        path = path.replace('{id}', quote(str(path_values['id']), safe=''))
        query = None
        body = None
        return await self._transport.request(
            'GET',
            path,
            response_model=models.GetProfileResponse,
            query=query,
            body=body,
            options=_request_options,
        )

    async def list(
        self,
        *,
        page: int | None = None,
        limit: int | None = None,
        name: str | None = None,
        _request_options: RequestOptions | None = None,
    ) -> models.ListProfilesResponse:
        """List profiles for this project"""
        path = '/v1/profiles/'
        query = models.ListProfilesQuery.model_validate(
            {'page': page, 'limit': limit, 'name': name}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        body = None
        return await self._transport.request(
            'GET',
            path,
            response_model=models.ListProfilesResponse,
            query=query,
            body=body,
            options=_request_options,
        )

    async def update(
        self,
        id: str,
        *,
        name: str | None = None,
        description: str | None = None,
        _request_options: RequestOptions | None = None,
    ) -> models.UpdateProfileResponse:
        """Update a profile"""
        path_values = models.UpdateProfilePath.model_validate(
            {'id': id}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        path = '/v1/profiles/{id}'
        path = path.replace('{id}', quote(str(path_values['id']), safe=''))
        query = None
        body = models.UpdateProfileBody.model_validate(
            {'name': name, 'description': description}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        return await self._transport.request(
            'PATCH',
            path,
            response_model=models.UpdateProfileResponse,
            query=query,
            body=body,
            options=_request_options,
        )


class AsyncAppsResource(_AsyncResource):
    async def create(
        self,
        platform: models.CreateAppPlatform | str,
        name: str,
        client_id: str,
        client_secret: str,
        *,
        image_url: str | None = None,
        _request_options: RequestOptions | None = None,
    ) -> models.CreateAppResponse:
        """Register your own OAuth app (Bring Your Own Keys)"""
        path = '/v1/apps/'
        query = None
        body = models.CreateAppBody.model_validate(
            {'platform': platform, 'name': name, 'clientId': client_id, 'clientSecret': client_secret, 'imageUrl': image_url}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        return await self._transport.request(
            'POST',
            path,
            response_model=models.CreateAppResponse,
            query=query,
            body=body,
            options=_request_options,
        )

    async def delete(
        self,
        id: str,
        *,
        _request_options: RequestOptions | None = None,
    ) -> models.DeleteAppResponse:
        """Delete an OAuth app"""
        path_values = models.DeleteAppPath.model_validate(
            {'id': id}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        path = '/v1/apps/{id}'
        path = path.replace('{id}', quote(str(path_values['id']), safe=''))
        query = None
        body = None
        return await self._transport.request(
            'DELETE',
            path,
            response_model=models.DeleteAppResponse,
            query=query,
            body=body,
            options=_request_options,
        )

    async def get(
        self,
        id: str,
        *,
        _request_options: RequestOptions | None = None,
    ) -> models.GetAppResponse:
        """Get a single OAuth app"""
        path_values = models.GetAppPath.model_validate(
            {'id': id}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        path = '/v1/apps/{id}'
        path = path.replace('{id}', quote(str(path_values['id']), safe=''))
        query = None
        body = None
        return await self._transport.request(
            'GET',
            path,
            response_model=models.GetAppResponse,
            query=query,
            body=body,
            options=_request_options,
        )

    async def list(
        self,
        *,
        platform: models.ListAppsPlatform | str | None = None,
        page: int | None = None,
        limit: int | None = None,
        name: str | None = None,
        _request_options: RequestOptions | None = None,
    ) -> models.ListAppsResponse:
        """List registered OAuth apps for this project"""
        path = '/v1/apps/'
        query = models.ListAppsQuery.model_validate(
            {'platform': platform, 'page': page, 'limit': limit, 'name': name}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        body = None
        return await self._transport.request(
            'GET',
            path,
            response_model=models.ListAppsResponse,
            query=query,
            body=body,
            options=_request_options,
        )

    async def update(
        self,
        id: str,
        *,
        name: str | None = None,
        image_url: str | None = None,
        client_secret: str | None = None,
        _request_options: RequestOptions | None = None,
    ) -> models.UpdateAppResponse:
        """Update an OAuth app"""
        path_values = models.UpdateAppPath.model_validate(
            {'id': id}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        path = '/v1/apps/{id}'
        path = path.replace('{id}', quote(str(path_values['id']), safe=''))
        query = None
        body = models.UpdateAppBody.model_validate(
            {'name': name, 'imageUrl': image_url, 'clientSecret': client_secret}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        return await self._transport.request(
            'PATCH',
            path,
            response_model=models.UpdateAppResponse,
            query=query,
            body=body,
            options=_request_options,
        )


class AsyncNotificationsResource(_AsyncResource):
    async def create(
        self,
        channel: models.CreateNotificationChannel | str,
        event_types: Sequence[models.CreateNotificationEventTypes | str],
        *,
        profile_id: str | None = None,
        only_scheduled_posts: bool | None = None,
        enabled: bool | None = None,
        webhook: models.CreateNotificationWebhook | Mapping[str, Any] | None = None,
        email: models.CreateNotificationEmail | Mapping[str, Any] | None = None,
        _request_options: RequestOptions | None = None,
    ) -> models.CreateNotificationResponse:
        """Create a notification subscription"""
        path = '/v1/notifications/'
        query = None
        body = models.CreateNotificationBody.model_validate(
            {'channel': channel, 'profileId': profile_id, 'eventTypes': event_types, 'onlyScheduledPosts': only_scheduled_posts, 'enabled': enabled, 'webhook': webhook, 'email': email}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        return await self._transport.request(
            'POST',
            path,
            response_model=models.CreateNotificationResponse,
            query=query,
            body=body,
            options=_request_options,
        )

    async def delete(
        self,
        id: str,
        *,
        _request_options: RequestOptions | None = None,
    ) -> models.DeleteNotificationResponse:
        """Delete a notification subscription"""
        path_values = models.DeleteNotificationPath.model_validate(
            {'id': id}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        path = '/v1/notifications/{id}'
        path = path.replace('{id}', quote(str(path_values['id']), safe=''))
        query = None
        body = None
        return await self._transport.request(
            'DELETE',
            path,
            response_model=models.DeleteNotificationResponse,
            query=query,
            body=body,
            options=_request_options,
        )

    async def get(
        self,
        id: str,
        *,
        _request_options: RequestOptions | None = None,
    ) -> models.GetNotificationResponse:
        """Get a notification subscription"""
        path_values = models.GetNotificationPath.model_validate(
            {'id': id}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        path = '/v1/notifications/{id}'
        path = path.replace('{id}', quote(str(path_values['id']), safe=''))
        query = None
        body = None
        return await self._transport.request(
            'GET',
            path,
            response_model=models.GetNotificationResponse,
            query=query,
            body=body,
            options=_request_options,
        )

    async def list(
        self,
        *,
        _request_options: RequestOptions | None = None,
    ) -> models.ListNotificationsResponse:
        """List notification subscriptions"""
        path = '/v1/notifications/'
        query = None
        body = None
        return await self._transport.request(
            'GET',
            path,
            response_model=models.ListNotificationsResponse,
            query=query,
            body=body,
            options=_request_options,
        )

    async def test(
        self,
        channel: models.TestNotificationChannel | str,
        *,
        profile_id: str | None = None,
        webhook: models.TestNotificationWebhook | Mapping[str, Any] | None = None,
        email: models.TestNotificationEmail | Mapping[str, Any] | None = None,
        _request_options: RequestOptions | None = None,
    ) -> models.TestNotificationResponse:
        """Test a notification destination before saving it"""
        path = '/v1/notifications/test'
        query = None
        body = models.TestNotificationBody.model_validate(
            {'channel': channel, 'profileId': profile_id, 'webhook': webhook, 'email': email}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        return await self._transport.request(
            'POST',
            path,
            response_model=models.TestNotificationResponse,
            query=query,
            body=body,
            options=_request_options,
        )

    async def update(
        self,
        id: str,
        *,
        profile_id: str | None = None,
        event_types: Sequence[models.UpdateNotificationEventTypes | str] | None = None,
        only_scheduled_posts: bool | None = None,
        enabled: bool | None = None,
        webhook: models.UpdateNotificationWebhook | Mapping[str, Any] | None = None,
        email: models.UpdateNotificationEmail | Mapping[str, Any] | None = None,
        _request_options: RequestOptions | None = None,
    ) -> models.UpdateNotificationResponse:
        """Update a notification subscription"""
        path_values = models.UpdateNotificationPath.model_validate(
            {'id': id}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        path = '/v1/notifications/{id}'
        path = path.replace('{id}', quote(str(path_values['id']), safe=''))
        query = None
        body = models.UpdateNotificationBody.model_validate(
            {'profileId': profile_id, 'eventTypes': event_types, 'onlyScheduledPosts': only_scheduled_posts, 'enabled': enabled, 'webhook': webhook, 'email': email}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        return await self._transport.request(
            'PATCH',
            path,
            response_model=models.UpdateNotificationResponse,
            query=query,
            body=body,
            options=_request_options,
        )


class AsyncPlatformsResource(_AsyncResource):
    async def list(
        self,
        *,
        _request_options: RequestOptions | None = None,
    ) -> models.ListPlatformsResponse:
        """List available platforms and their status"""
        path = '/v1/platforms'
        query = None
        body = None
        return await self._transport.request(
            'GET',
            path,
            response_model=models.ListPlatformsResponse,
            query=query,
            body=body,
            options=_request_options,
        )


class AsyncPostsScheduledResource(_AsyncResource):
    async def cancel(
        self,
        post_id: str,
        *,
        _request_options: RequestOptions | None = None,
    ) -> models.CancelScheduledPostResponse:
        """Cancel a scheduled post (moves it back to draft)"""
        path_values = models.CancelScheduledPostPath.model_validate(
            {'postId': post_id}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        path = '/v1/posts/scheduled/{postId}'
        path = path.replace('{postId}', quote(str(path_values['postId']), safe=''))
        query = None
        body = None
        return await self._transport.request(
            'DELETE',
            path,
            response_model=models.CancelScheduledPostResponse,
            query=query,
            body=body,
            options=_request_options,
        )

    async def list(
        self,
        *,
        limit: int | None = None,
        offset: int | None = None,
        sort: models.SortOrder | None = None,
        _request_options: RequestOptions | None = None,
    ) -> models.ListScheduledPostsResponse:
        """List all scheduled posts"""
        path = '/v1/posts/scheduled/'
        query = models.ListScheduledPostsQuery.model_validate(
            {'limit': limit, 'offset': offset, 'sort': sort}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        body = None
        return await self._transport.request(
            'GET',
            path,
            response_model=models.ListScheduledPostsResponse,
            query=query,
            body=body,
            options=_request_options,
        )

    async def reschedule(
        self,
        post_id: str,
        scheduled_for: str,
        *,
        timezone: str | None = None,
        _request_options: RequestOptions | None = None,
    ) -> models.ReschedulePostResponse:
        """Reschedule a post to a new time"""
        path_values = models.ReschedulePostPath.model_validate(
            {'postId': post_id}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        path = '/v1/posts/scheduled/{postId}'
        path = path.replace('{postId}', quote(str(path_values['postId']), safe=''))
        query = None
        body = models.ReschedulePostBody.model_validate(
            {'scheduledFor': scheduled_for, 'timezone': timezone}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        return await self._transport.request(
            'PATCH',
            path,
            response_model=models.ReschedulePostResponse,
            query=query,
            body=body,
            options=_request_options,
        )


class AsyncPostsResource(_AsyncResource):
    async def create(
        self,
        content: str,
        platforms: Sequence[models.CreatePostPlatforms | Mapping[str, Any] | models.CreatePostPlatforms_ | Mapping[str, Any] | models.CreatePostPlatforms_2 | Mapping[str, Any] | models.CreatePostPlatforms_3 | Mapping[str, Any] | models.CreatePostPlatforms_4 | Mapping[str, Any] | models.CreatePostPlatforms_5 | Mapping[str, Any] | models.CreatePostPlatforms_6 | Mapping[str, Any] | models.CreatePostPlatforms_7 | Mapping[str, Any] | models.CreatePostPlatforms_8 | Mapping[str, Any] | models.CreatePostPlatforms_9 | Mapping[str, Any]],
        *,
        media_items: Sequence[models.CreatePostMediaItems | Mapping[str, Any]] | None = None,
        publish_now: bool | None = None,
        scheduled_for: str | None = None,
        timezone: str | None = None,
        _request_options: RequestOptions | None = None,
    ) -> models.CreatePostResponse:
        """Publish a post to one or more social media platforms"""
        path = '/v1/posts/'
        query = None
        body = models.CreatePostBody.model_validate(
            {'content': content, 'mediaItems': media_items, 'platforms': platforms, 'publishNow': publish_now, 'scheduledFor': scheduled_for, 'timezone': timezone}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        return await self._transport.request(
            'POST',
            path,
            response_model=models.CreatePostResponse,
            query=query,
            body=body,
            options=_request_options,
        )

    async def delete(
        self,
        post_id: str,
        *,
        delete_from_platforms: bool | None = None,
        _request_options: RequestOptions | None = None,
    ) -> models.DeletePostResponse:
        """Delete a post by ID"""
        path_values = models.DeletePostPath.model_validate(
            {'postId': post_id}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        path = '/v1/posts/{postId}'
        path = path.replace('{postId}', quote(str(path_values['postId']), safe=''))
        query = models.DeletePostQuery.model_validate(
            {'deleteFromPlatforms': delete_from_platforms}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        body = None
        return await self._transport.request(
            'DELETE',
            path,
            response_model=models.DeletePostResponse,
            query=query,
            body=body,
            options=_request_options,
        )

    async def get(
        self,
        post_id: str,
        *,
        _request_options: RequestOptions | None = None,
    ) -> models.GetPostResponse:
        """Get a single post by ID"""
        path_values = models.GetPostPath.model_validate(
            {'postId': post_id}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        path = '/v1/posts/{postId}'
        path = path.replace('{postId}', quote(str(path_values['postId']), safe=''))
        query = None
        body = None
        return await self._transport.request(
            'GET',
            path,
            response_model=models.GetPostResponse,
            query=query,
            body=body,
            options=_request_options,
        )

    async def list(
        self,
        *,
        status: models.ListPostsStatus | str | None = None,
        platform: Sequence[models.ListPostsPlatform | str] | None = None,
        profile_id: str | None = None,
        created_after: str | None = None,
        created_before: str | None = None,
        scheduled_after: str | None = None,
        scheduled_before: str | None = None,
        limit: int | None = None,
        offset: int | None = None,
        sort: models.SortOrder | None = None,
        _request_options: RequestOptions | None = None,
    ) -> models.ListPostsResponse:
        """List all posts for the project"""
        path = '/v1/posts/'
        query = models.ListPostsQuery.model_validate(
            {'status': status, 'platform': platform, 'profileId': profile_id, 'createdAfter': created_after, 'createdBefore': created_before, 'scheduledAfter': scheduled_after, 'scheduledBefore': scheduled_before, 'limit': limit, 'offset': offset, 'sort': sort}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        body = None
        return await self._transport.request(
            'GET',
            path,
            response_model=models.ListPostsResponse,
            query=query,
            body=body,
            options=_request_options,
        )

    @cached_property
    def scheduled(self) -> AsyncPostsScheduledResource:
        return AsyncPostsScheduledResource(self._transport)


class AsyncMediaResource(_AsyncResource):
    async def upload(
        self,
        filename: str,
        mime_type: str,
        *,
        _request_options: RequestOptions | None = None,
    ) -> models.CreateMediaUploadResponse:
        """Get a presigned S3 URL to upload a media file"""
        path = '/v1/media/upload'
        query = None
        body = models.CreateMediaUploadBody.model_validate(
            {'filename': filename, 'mimeType': mime_type}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        return await self._transport.request(
            'POST',
            path,
            response_model=models.CreateMediaUploadResponse,
            query=query,
            body=body,
            options=_request_options,
        )


class AsyncAnalyticsResource(_AsyncResource):
    async def get(
        self,
        *,
        post_id: str | None = None,
        platform: models.Platform | None = None,
        account_id: str | None = None,
        source: models.GetAnalyticsSource | str | None = None,
        from_date: str | None = None,
        to_date: str | None = None,
        sort_by: models.GetAnalyticsSortBy | str | None = None,
        order: models.SortOrder | None = None,
        limit: int | None = None,
        page: int | None = None,
        _request_options: RequestOptions | None = None,
    ) -> models.GetAnalyticsResponse:
        """Get post analytics"""
        path = '/v1/analytics/'
        query = models.GetAnalyticsQuery.model_validate(
            {'postId': post_id, 'platform': platform, 'accountId': account_id, 'source': source, 'fromDate': from_date, 'toDate': to_date, 'sortBy': sort_by, 'order': order, 'limit': limit, 'page': page}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        body = None
        return await self._transport.request(
            'GET',
            path,
            response_model=models.GetAnalyticsResponse,
            query=query,
            body=body,
            options=_request_options,
        )


class AsyncUsageResource(_AsyncResource):
    async def get(
        self,
        *,
        profile_id: str | None = None,
        integration_id: str | None = None,
        from_: str | None = None,
        to: str | None = None,
        _request_options: RequestOptions | None = None,
    ) -> models.GetUsageResponse:
        """Get credit usage"""
        path = '/v1/usage/'
        query = models.GetUsageQuery.model_validate(
            {'profileId': profile_id, 'integrationId': integration_id, 'from': from_, 'to': to}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        body = None
        return await self._transport.request(
            'GET',
            path,
            response_model=models.GetUsageResponse,
            query=query,
            body=body,
            options=_request_options,
        )


class AsyncPinterestResource(_AsyncResource):
    async def get_boards(
        self,
        *,
        account_id: str | None = None,
        _request_options: RequestOptions | None = None,
    ) -> models.GetPinterestBoardsResponse:
        """List Pinterest boards for a connected account"""
        path = '/v1/pinterest/boards'
        query = models.GetPinterestBoardsQuery.model_validate(
            {'accountId': account_id}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        body = None
        return await self._transport.request(
            'GET',
            path,
            response_model=models.GetPinterestBoardsResponse,
            query=query,
            body=body,
            options=_request_options,
        )


class AsyncTiktokResource(_AsyncResource):
    async def get_creator_info(
        self,
        *,
        account_id: str | None = None,
        _request_options: RequestOptions | None = None,
    ) -> models.GetTikTokCreatorInfoResponse:
        """Fetch TikTok creator info for a connected account"""
        path = '/v1/tiktok/creator-info'
        query = models.GetTikTokCreatorInfoQuery.model_validate(
            {'accountId': account_id}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        body = None
        return await self._transport.request(
            'GET',
            path,
            response_model=models.GetTikTokCreatorInfoResponse,
            query=query,
            body=body,
            options=_request_options,
        )


class AsyncAiResource(_AsyncResource):
    async def generate_image(
        self,
        description: str,
        *,
        aspect_ratio: models.AiGenerateImageAspectRatio | str | None = None,
        style: models.AiGenerateImageStyle | str | None = None,
        reference_image_urls: Sequence[str] | None = None,
        asset_image_urls: Sequence[str] | None = None,
        reference_image_url: str | None = None,
        _request_options: RequestOptions | None = None,
    ) -> models.AiGenerateImageResponse:
        """Generate a social media image from a description"""
        path = '/v1/ai/image'
        query = None
        body = models.AiGenerateImageBody.model_validate(
            {'description': description, 'aspectRatio': aspect_ratio, 'style': style, 'referenceImageUrls': reference_image_urls, 'assetImageUrls': asset_image_urls, 'referenceImageUrl': reference_image_url}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        return await self._transport.request(
            'POST',
            path,
            response_model=models.AiGenerateImageResponse,
            query=query,
            body=body,
            options=_request_options,
        )

    async def write(
        self,
        description: str,
        *,
        platforms: Sequence[models.AiWriteContentPlatforms | str] | None = None,
        existing_content: str | None = None,
        _request_options: RequestOptions | None = None,
    ) -> models.AiWriteContentResponse:
        """Generate a social media caption from a description"""
        path = '/v1/ai/write'
        query = None
        body = models.AiWriteContentBody.model_validate(
            {'description': description, 'platforms': platforms, 'existingContent': existing_content}
        ).model_dump(mode="json", by_alias=True, exclude_none=True)
        return await self._transport.request(
            'POST',
            path,
            response_model=models.AiWriteContentResponse,
            query=query,
            body=body,
            options=_request_options,
        )


class AsyncPostPeerResources(_AsyncResource):
    @cached_property
    def ai(self) -> AsyncAiResource:
        return AsyncAiResource(self._transport)

    @cached_property
    def analytics(self) -> AsyncAnalyticsResource:
        return AsyncAnalyticsResource(self._transport)

    @cached_property
    def apps(self) -> AsyncAppsResource:
        return AsyncAppsResource(self._transport)

    @cached_property
    def connect(self) -> AsyncConnectResource:
        return AsyncConnectResource(self._transport)

    @cached_property
    def health(self) -> AsyncHealthResource:
        return AsyncHealthResource(self._transport)

    @cached_property
    def media(self) -> AsyncMediaResource:
        return AsyncMediaResource(self._transport)

    @cached_property
    def notifications(self) -> AsyncNotificationsResource:
        return AsyncNotificationsResource(self._transport)

    @cached_property
    def pinterest(self) -> AsyncPinterestResource:
        return AsyncPinterestResource(self._transport)

    @cached_property
    def platforms(self) -> AsyncPlatformsResource:
        return AsyncPlatformsResource(self._transport)

    @cached_property
    def posts(self) -> AsyncPostsResource:
        return AsyncPostsResource(self._transport)

    @cached_property
    def profiles(self) -> AsyncProfilesResource:
        return AsyncProfilesResource(self._transport)

    @cached_property
    def tiktok(self) -> AsyncTiktokResource:
        return AsyncTiktokResource(self._transport)

    @cached_property
    def usage(self) -> AsyncUsageResource:
        return AsyncUsageResource(self._transport)


__all__ = ['AsyncPostPeerResources', 'SyncPostPeerResources']
